language: python
cache: pip
sudo: false

python:
  - "2.7"
  - "3.5"
  - "3.6"

branches:
  only:
    - master

install:
  - pip install --upgrade pytest
  # ensure pip install finds all dependencies
  - pip install -e .


script:
  - pytest -v
