language: python
cache: pip
sudo: false

python:
  - "2.7"

branches:
  only:
    - master

install:
  - pip install --upgrade numpy scipy numba pandas matplotlib
  - pip install -e .


script:
  - cd pydhamed/tests/
  - nosetests -v
 
